#requires -Version 3
#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 16d9acc8-9b63-4b4b-9fc7-90110eb0ac40
# Source File: DellESCFinder.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
3gMAAB+LCAAAAAAABABlk8mOo1gQRfeW/A+p2iIVZrAxUlZKzIOZMWbYgRke02M0YL6+srM3LXWs
QqF7N3F0Pp3s2S3Z+ObjOf74Xqayg39+Eb+xX1/Hw8fHpzmWRQnjRiybzIjb7IvPmkZwObGEaTb+
7qf8E/1f5qcpdmP7dUppDxMbJWVWhuFMnmP+HZbhm0eDW23NeLmPuujOgzauCpbuCtf3sNgfiBa/
ERUeM/75edlVAHCpR/PwaR0PA+Z73QMS/V0AzJJXmY6cN0pAkf1aCArc6QLjUijxm0Ty4ZVIVFsr
sTFTwGuDp77bZJAG8sOnT7NQHQ9XzilTYxvT5GZV89sr1TvfCspgcuElqwEtFF4eJmkRX9iKoNTV
QgqrEiWCPRPAFXRvo7Q9xaB1Evn1eBBVyX7vlRE9nNUBygzeLWtBDmfcMx49NerBM8vK3F8dAB1b
3yQeOnVqErg12i/a0TU7MNqpMeaqnsrjodNvWj61QtA+O2QDUpLe6EXqTXQ2hnDLVtGpfblH5HtP
N9SuvnbIhliztQSC4SgMc79GoWzNTDKR8Hh4Jz25qkjFsBGZhkTErfemw6hV1Kn2GZFrtAq+MOat
JP7DDf/mdkuEc3HLbP9lxyHjvsVrkZ8sQ3Hn4+FcbI8O6k4jlzZrOaaSNSNTXjSDUBirk6YVZLYc
NMJjy9uIempNDEZ1mC5h+kqGU6JYFZW0E1E/WxY9HmITKpfytS84Au/aEjW58jZJjByxu3r1IrgS
fq6LGJsp3MmS+8v0uhl4sIhVcuXtIUn48FkjifEYqZw6HkADexTLgmUdtglc9DBBNn59e7nL8aDu
p4teeLUyqzWrTJJ1XahMHsxYNmU4VP0SreiM0vUS2X5CmMeD3L2DWUnVW+FWxju3dnrRI8vvzyg5
Fhh2lxfxcivmwLNA4OFepiXw0XeDJUvAU8YTSdb16jKYQdL+9980SwhVt27hXDityRbUXeMQM7iG
CFRtHFktAEsd0qQTGLKBvpYy15Oa3Lw9sPVvdf58oj9q/UjGTFPWJk2ZTR/o9+UT/a/PX38BJZpb
Rd4DAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Form code generated by:  PowerShell Studio 2019
     Generated on:       	  8/1/2019 9:07 AM
	 Powershell Logic by:     Alan Newingham
	 Contact: 		   	      alan.newingham@gmail.com
	 Git:					  https://github.com/01000001-01001110/Share
	--------------------------------------------------------------------------------
#>

#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-DellESCFinder_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$labelServiceTag = New-Object 'System.Windows.Forms.Label'
	$textbox2 = New-Object 'System.Windows.Forms.TextBox'
	$labelDellExpressServiceTa = New-Object 'System.Windows.Forms.Label'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$buttonFindESC = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$form1_Load={
		#TODO: Initialize Form Controls here
		
	}
	function Find-ESC {
		Begin { }
	
		Process
		{
			$ValB36 = $textbox1.Text
			$Range = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
			$ca = $ValB36.ToUpper().ToCharArray()
			[System.Array]::Reverse($ca)
			[System.Int64]$ValB10 = 0
			
			$i = 0
			foreach ($c in $ca) {
				$ValB10 += $Range.IndexOf($c) * [System.Int64][System.Math]::Pow(36, $i)
				$i += 1
			}
			
			$Textbox2.Text = $ValB10
			$Textbox1.Text = $ValB36
			
		}
	
		End { }
			
		}
	
	$textbox1_TextChanged={
		#TODO: Place custom script here
		
	}
	
	$textbox2_TextChanged={
		#TODO: Place custom script here
		
	}
	
	$buttonFindESC_Click={
		Find-ESC
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$textbox2.remove_TextChanged($textbox2_TextChanged)
			$textbox1.remove_TextChanged($textbox1_TextChanged)
			$buttonFindESC.remove_Click($buttonFindESC_Click)
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($labelServiceTag)
	$form1.Controls.Add($textbox2)
	$form1.Controls.Add($labelDellExpressServiceTa)
	$form1.Controls.Add($textbox1)
	$form1.Controls.Add($buttonFindESC)
	$form1.AutoScaleDimensions = '6, 13'
	$form1.AutoScaleMode = 'Font'
	$form1.ClientSize = '408, 111'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# labelServiceTag
	#
	$labelServiceTag.AutoSize = $True
	$labelServiceTag.Location = '13, 52'
	$labelServiceTag.Name = 'labelServiceTag'
	$labelServiceTag.Size = '68, 17'
	$labelServiceTag.TabIndex = 8
	$labelServiceTag.Text = 'Service Tag:'
	$labelServiceTag.UseCompatibleTextRendering = $True
	#
	# textbox2
	#
	$textbox2.Location = '87, 75'
	$textbox2.Name = 'textbox2'
	$textbox2.Size = '233, 20'
	$textbox2.TabIndex = 7
	$textbox2.add_TextChanged($textbox2_TextChanged)
	#
	# labelDellExpressServiceTa
	#
	$labelDellExpressServiceTa.AutoSize = $True
	$labelDellExpressServiceTa.Location = '112, 13'
	$labelDellExpressServiceTa.Name = 'labelDellExpressServiceTa'
	$labelDellExpressServiceTa.Size = '185, 17'
	$labelDellExpressServiceTa.TabIndex = 6
	$labelDellExpressServiceTa.Text = 'Dell Express Service Tag Calculator'
	$labelDellExpressServiceTa.UseCompatibleTextRendering = $True
	#
	# textbox1
	#
	$textbox1.Location = '87, 49'
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '233, 20'
	$textbox1.TabIndex = 1
	$textbox1.add_TextChanged($textbox1_TextChanged)
	#
	# buttonFindESC
	#
	$buttonFindESC.Location = '326, 47'
	$buttonFindESC.Name = 'buttonFindESC'
	$buttonFindESC.Size = '75, 23'
	$buttonFindESC.TabIndex = 0
	$buttonFindESC.Text = 'Find ESC'
	$buttonFindESC.UseCompatibleTextRendering = $True
	$buttonFindESC.UseVisualStyleBackColor = $True
	$buttonFindESC.add_Click($buttonFindESC_Click)
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Show-DellESCFinder_psf | Out-Null
