#requires -Version 3
#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 16d9acc8-9b63-4b4b-9fc7-90110eb0ac40
# Source File: DellESCFinder.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
RgQAAB+LCAAAAAAABABlVMmOo1oM3UfiH0q9RWq4IQyRqkpiDiTMXALZMYcxDAECX9959TYttVeW
ZUs+5/j4007jx5wOqxA+w493MhaP9usX8Rv8+kZ2Hx+fxlDkRRvWUlGnetik30Ja16LDS0WbpMPv
bsw+sX96fialx9B8uzd/AVwQ2ZzIsrwh8Oz/wbFC7YG92VQszK6Yg23C/QGPlWQLtlfhPQidLnJT
Kbpjen6Jp+QqaJq8gpk+bMjuIYE9tNtnONw6l82zI6otR2Z74eYYYwpvdQfDv7yEXrJTZSAzC9Av
sBYyit6DWsMe22x3rnRPTqcUUMiuO2tRINdiRdBDX9SY0SrbUmoyZlnrVgo27sNrxZcMK0/ZpRA6
7kAJdMJNMtgPXAwMD9fUsvJbmjqn793C06IXyqZOCl6vYQxvam/AhTuqg626PEoUDrO5JbCqLfdt
W1AqWcEvoSGcZ3+vRNfOpyrtyMrBUe6QnT7Gb7bduCAoldOerxuHlvrUuIbcC5ju9QEBgjhopFfi
W/iNeMxBE0Fhi4C6nRlwKDP6oQ821nJswiK7rSRNZZg0rxrlMH1w0+HJx4bXn8hyaatT7aDUJvDD
AKt9gHPclntMJKvhmxCSd0q5NH3WY/Inc3+KHrKrTyw8tHg8i8dm5BTyP63bt9Y3ORcEWI/D67rO
VFTo6bm+qgab8xvgoD1Lhb+ZcA7DlyXCPnM1w4iRndpkLSR5Qg7mvm2ZuEgPZOCHtVna+s0LYbN2
7hJJ4CbdJIpj3WnsxEoqLLErSptGt5e4h7fufshEkCO7QjMkZ6lrFDMvRgFFDSyMr6ldNqF2wAF9
Yuce7EMa9e8oTPYrsFuKPwerk0zJA/XONlwuVUN6Ts69L0QtlLpf6I6a1vEQqqYlZU1vdfVVVqay
xxmswTEyaqJ64v03oBOzzxZjXzvE1K1JAqJWe92T/Nhdh4FGdsKeIPs8Wy5NErbGzcCIvgqzE4yC
Z2fAbLDMafbZJ3VPzVoGjsMbdiE2gRgzA+rQ4gHVPff8Cp5Sii3IzuLXvl1V82wHdH9M1Xsmw6CV
XtY2rISqJf1VzqjqLgFCD+HszdVxdfpeIpOOhMv5ALrweqGvFYWyhIrsJL7Ef7zKfn19Yj8W/jEz
O47pG1+Rjh/Yu/KJ/f03vv8Am+fcaUYEAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Form code generated by:  PowerShell Studio 2019
     Generated on:       	  8/2/2019 9:07 AM
	 Powershell Logic by:     Alan Newingham
	 Contact: 		   	      alan.newingham@gmail.com
	 Git:					  https://github.com/01000001-01001110/Share
	--------------------------------------------------------------------------------
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-DellESCFinder_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$labelExpressServiceCode = New-Object 'System.Windows.Forms.Label'
	$buttonFindST = New-Object 'System.Windows.Forms.Button'
	$labelServiceTag = New-Object 'System.Windows.Forms.Label'
	$textbox2 = New-Object 'System.Windows.Forms.TextBox'
	$labelExpressServiceCodeSe = New-Object 'System.Windows.Forms.Label'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$buttonFindESC = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$form1_Load={
		#TODO: Initialize Form Controls here
		
	}
	function Find-ESC {
		Begin { }
	
		Process
		{
			$ValB36 = $textbox1.Text
			$Range = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
			$ca = $ValB36.ToUpper().ToCharArray()
			[System.Array]::Reverse($ca)
			[System.Int64]$ValB10 = 0
			
			$i = 0
			foreach ($c in $ca) {
				$ValB10 += $Range.IndexOf($c) * [System.Int64][System.Math]::Pow(36, $i)
				$i += 1
			}
			
			$Textbox2.Text = $ValB10
			$Textbox1.Text = $ValB36
			
		}
	
		End { }
			
		}

		function Find-ST
		{
			Begin{}
	 
			Process{
				$Alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
				$Base36 = ''
				$OriginalVal = $Textbox2.Text
				$Base10 = $Textbox2.Text
				do
				{
					$r = $Base10 % 36
					$c = $Alphabet.Substring($r,1)
					$Base36 = "$c$Base36"
					$Base10 = ($Base10 - $r)/36
				} while ($Base10 -gt 0)
		 
				$Textbox2.Text = $OriginalVal
				$Textbox1.Text = $Base36
			}
		 
			End{}
		 
		}
	
	$textbox1_TextChanged={
		#TODO: Place custom script here
		
	}
	
	$textbox2_TextChanged={
		#TODO: Place custom script here
		
	}
	
	$buttonFindESC_Click={
		Find-ESC
		
	}
	
	$buttonFindST_Click={
		Find-ST
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonFindST.remove_Click($buttonFindST_Click)
			$textbox2.remove_TextChanged($textbox2_TextChanged)
			$textbox1.remove_TextChanged($textbox1_TextChanged)
			$buttonFindESC.remove_Click($buttonFindESC_Click)
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($labelExpressServiceCode)
	$form1.Controls.Add($buttonFindST)
	$form1.Controls.Add($labelServiceTag)
	$form1.Controls.Add($textbox2)
	$form1.Controls.Add($labelExpressServiceCodeSe)
	$form1.Controls.Add($textbox1)
	$form1.Controls.Add($buttonFindESC)
	$form1.AutoScaleDimensions = '6, 13'
	$form1.AutoScaleMode = 'Font'
	$form1.ClientSize = '377, 131'
	$form1.Name = 'form1'
	$form1.Text = 'ESC/ST Calculator'
	$form1.add_Load($form1_Load)
	#
	# labelExpressServiceCode
	#
	$labelExpressServiceCode.AutoSize = $True
	$labelExpressServiceCode.Location = '13, 78'
	$labelExpressServiceCode.Name = 'labelExpressServiceCode'
	$labelExpressServiceCode.Size = '119, 17'
	$labelExpressServiceCode.TabIndex = 10
	$labelExpressServiceCode.Text = 'Express Service Code:'
	$labelExpressServiceCode.UseCompatibleTextRendering = $True
	#
	# buttonFindST
	#
	$buttonFindST.Location = '296, 102'
	$buttonFindST.Name = 'buttonFindST'
	$buttonFindST.Size = '75, 23'
	$buttonFindST.TabIndex = 9
	$buttonFindST.Text = 'Find ST'
	$buttonFindST.UseCompatibleTextRendering = $True
	$buttonFindST.UseVisualStyleBackColor = $True
	$buttonFindST.add_Click($buttonFindST_Click)
	#
	# labelServiceTag
	#
	$labelServiceTag.AutoSize = $True
	$labelServiceTag.Location = '13, 52'
	$labelServiceTag.Name = 'labelServiceTag'
	$labelServiceTag.Size = '68, 17'
	$labelServiceTag.TabIndex = 8
	$labelServiceTag.Text = 'Service Tag:'
	$labelServiceTag.UseCompatibleTextRendering = $True
	#
	# textbox2
	#
	$textbox2.Location = '138, 75'
	$textbox2.Name = 'textbox2'
	$textbox2.Size = '233, 20'
	$textbox2.TabIndex = 7
	$textbox2.add_TextChanged($textbox2_TextChanged)
	#
	# labelExpressServiceCodeSe
	#
	$labelExpressServiceCodeSe.AutoSize = $True
	$labelExpressServiceCodeSe.Location = '70, 13'
	$labelExpressServiceCodeSe.Name = 'labelExpressServiceCodeSe'
	$labelExpressServiceCodeSe.Size = '237, 17'
	$labelExpressServiceCodeSe.TabIndex = 6
	$labelExpressServiceCodeSe.Text = 'Express Service Code / Service Tag Calculator'
	$labelExpressServiceCodeSe.UseCompatibleTextRendering = $True
	#
	# textbox1
	#
	$textbox1.Location = '138, 49'
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '233, 20'
	$textbox1.TabIndex = 1
	$textbox1.add_TextChanged($textbox1_TextChanged)
	#
	# buttonFindESC
	#
	$buttonFindESC.Location = '215, 102'
	$buttonFindESC.Name = 'buttonFindESC'
	$buttonFindESC.Size = '75, 23'
	$buttonFindESC.TabIndex = 0
	$buttonFindESC.Text = 'Find ESC'
	$buttonFindESC.UseCompatibleTextRendering = $True
	$buttonFindESC.UseVisualStyleBackColor = $True
	$buttonFindESC.add_Click($buttonFindESC_Click)
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Show-DellESCFinder_psf | Out-Null
