#requires -Version 3
#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: a3bb8560-a207-4a70-963f-0eca49258683
# Source File: Fr33Bas3.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
sQYAAB+LCAAAAAAABABllcfO6zgShfcG/A4XvTXQygn4+wLK0crB0k7JyjlY0tO3585mgOGqwCIJ
sljnfD92ng57Pp9cvMa/vsFSDf0/fyF/Q3/9vt9+/fox5qqo+rgVqjbX4y7/LcwIwsQL8ve4vH+A
/0v/2SQMc/e7ZaoaqmPXr2SaZg2Opf87GJrzu3Xd4Kuwyo18wVJavLWVHUbdtAO58LdRWIIOmTRk
jDxGmVVQ1+zBg9KEuN8obqvmp3NkDrOeIGh/TIYZgF54uDXu5K8pAag3P5QNZa47KyCthDHhTJZQ
RIwGI7T5W0aqxoRkrYqf95sG6C8ae1GRyhCf0ZCP7L2VUU+JaalNXoFtIaaoddUx+5Q+aksFKm0W
X0tDJq838dA30IAii0xbrOPC+81yhdzaoj3VUCXDPoc7HgRIWLgqlLxuWBa4C6HGVbXjpROzwG/D
X2xtjRNYWb1F7Gg16fS2cg3qyZb3m2np0bX6bRqULs6nQbNgAz02cXh94sYvnwNAFh/Oz2iioaZL
GnjigO15fcF2AcsgyUYixIJmqrUydN1vTnYRBM6MPOJKqVa98VMiHtvoSO33bvYbcEnCgaKCWi2C
Nvm9Wc6cmHeNoL/r6eqgLTFrYCs+S2Sp7zcPClQM+aj8q1v7N0p3nKKXIR1RNcDLr4b1fRj64Dk7
x5zVsRGveExFBqKCnaMEYE+rPqHXk0cfit8P95vw0aqccU0Df0YuuJqgd4kGE7BHDF1ouoDE40kr
U0Wi0vCIiyYKimRq7aBhR5XC+OkwHJyT3yyKoNJ0v6VOX6/4TG7O2czbQnPNaKYl2apx5C5x1NSy
LtWQJOIk/kGircit2FQsk5AlCkUitKA4rffkt0Y8NeN+AxOax2Tp4b22Pt44uzTdwJJNSZ5SsVxD
ulnL1o03OPGDBmaxVl+5nF6yi5/RIadqnCpd3xS31+Z4/f2Gcxr84brhhD9tQuzafzSCfzWCA5MP
k1dwKvh2ZUfZU1ywxXYkTD0puoz+VF9cGxdDDYDaCbNVkvjd/dZgBqlBqYSlR069fFvb9X0NQ0XI
tHxIog+yCSP1eCaZDuoZIUxWx2Eh4Humac8QBIp++JqlLn4gbQB+X2p5ftJvm4HsVBwnhHNYy9X5
H8OwcGSzaRYRIO2Jwf6AdKh1Ni2lrBI6PRwmfuSxCphe7hqPM89RJ/v+QqIyvr+9CPYR5533rfwk
AjnKvJq4B+B1zPsnPLYMYBTAxZMX9HQKvO09q2q+LdVKXkYFgDpMQl553lf1OWL6ImsrnfkMwPRq
opa8aBK2FC7NMgeRfNJR66XY0myZkGoRDhchiBr33XLOAC5kB5Trn3QWlmh+vwUFRIByhrcqtuPX
zLt90oJt2UFvldhquxWmgLRhZ2pERraptFx3U7ZbKVP6WFzjI8FFHRPIwIygkfyq/oyxYffQT6jy
KODpx5vvyUIXU4QfBheRLB3eHsM0+oMlTmoITxyc6ZFVBcf2IcGVAfYhOydUTBxU+jrS4ZupZ9RG
eLXHWTzVt0gri5J05bb308qojsvCYdQnPpivBUp1+/tKXDfzOOFA0xPhrcwm624StkC/33IQ8UFY
GaYaS2BqHOE1/5qniAvJqkO2zsYWxdIFwQJjheLMXqu6a48NMnRkMqo4zwSYHKkHxl1H+D3t8Rh6
Rh1Mu+Gytn1NvpWoxDrHFtuvXtMV+iqfOsCR14epLJslaXszMF22VJ6/jq6eexGiVB3tvs7F3G8h
yyYNFFZfJPzzA/xBxh940MuSd0lb5csv4DvzA/wvon7/C/GS+jmxBgAA#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Form code generated by:  PowerShell Studio 2019
     Generated on:       8/5/2019 9:42 AM
     Powershell Logic by:     Alan Newingham
	 Contact: 		   	      alan.newingham@gmail.com
	 Git:					  https://github.com/01000001-01001110/Share
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2019
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-Fr33Bas3_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formFr33Bas3V001 = New-Object 'System.Windows.Forms.Form'
	$groupbox2 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonEncodeImage = New-Object 'System.Windows.Forms.Button'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$buttonDecodeImage = New-Object 'System.Windows.Forms.Button'
	$labelImageLocation = New-Object 'System.Windows.Forms.Label'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$richtextbox1 = New-Object 'System.Windows.Forms.RichTextBox'
	$buttonEncode64 = New-Object 'System.Windows.Forms.Button'
	$buttonDecode64 = New-Object 'System.Windows.Forms.Button'
	$statusbar1 = New-Object 'System.Windows.Forms.StatusBar'
	$buttonCopyToClipboard = New-Object 'System.Windows.Forms.Button'
	$linklabelCreatedByAlanNewingh = New-Object 'System.Windows.Forms.LinkLabel'
	$labelAltF4ForDirections = New-Object 'System.Windows.Forms.Label'
	$labelWelcomeToFr33Bas3The = New-Object 'System.Windows.Forms.Label'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formFr33Bas3V001_Load={
		#TODO: Initialize Form Controls here
		
	}
	#requires -Version 3
	#------------------------------------------------------------------------
	# Source File Information (DO NOT MODIFY)
	# Source ID: 59aa670b-13ff-441b-9b86-8c87fe29d6e5
	# Source File: ..\..\..\SAPIEN\PowerShell Studio\Files\AboutForm.psf
	#------------------------------------------------------------------------
	#region File Recovery Data (DO NOT MODIFY)
	<#RecoveryData:
	Wg8AAB+LCAAAAAAABABlV8cOhEqSvLfU/zCaK9LgnfRmJHzTNLZxzQ3vvefrl/dmZ7Wr5ZKlKigl
	kZGZkX9Yadxv6XTy4RL+7V7MZd/98+/oP+C//+v5+Nvf/tCnMi+7sBHLJtXCNv0XE/XrIvZT+49h
	zv4A/9/5X1/9ef6vXWQ1UfHgyYIYhtN5jvn3wzJ807qr3de5d9CARvHzj46YLXmZCrcWa0IlpxJS
	uSJPyrkHvVLyPqvbJ5Elv+cDtp1rpR04cNDZFq7ZYyUX3+g9Ky452+XBv+zXgcUUQAdrYg9ZV63J
	JpA7vKfV1clxtuAEZAvrTAHV89HKtgFeNJwVNgHzwnFGOwYsE4h+UDpLB9kKGJ99AVr8FmwdrBzI
	nDuKwS9fASsOIwC9OrZ5T70eS+nnw1gxvciB5GTw4jqznHPwGJdmn4P89Vi/RYxyNCbkOeFISo9f
	gplFu8trzhSo2P79bhsSf4pd0+PpJT8f1FUQiBki3irYxbbz4EQEFPlltQ7sezY201KirS95Inz1
	Y4KQFoQU/WFOuQpUsnYJOBZ9RsU6KlgX/3ysV/PFdKHXyF0ShoIFYf2FBQVaI3glx1Fdyq0FU+Li
	woRYke+OBV846tnuNO0mXWaS+LVD8xdlNiiVz0dF/GbMAPmFTnlQIso6mWsYMNSTRCNIGPZkZXZ+
	tytCQ2MtJM8CoQ0duOrPSlBLvL0UmAPxszyy7LCejz4DCDYi8gGCM2ohMn0a0FWFJF2UQGC3lK7L
	moP16fAyOtptw2L7BeBxSrxjbnPd0VHiaMfQx6uQsM8HyUx2DvKn4yzsrBKcwGFi/xMAJXc43pSS
	XMCZN8HYrjy2sly2XIuQQQCLKnwqQa4qSunKtczUjFNzz0edmzXnFF+u65U0H4i/bD8okpOftWTb
	+rwwHB7fazM/zbzkOFmW8wJi+YGrzPFUxsr0JmwspMV9PkKFMfT8Pz5wdpLPJcs7Hwdn/CEfF/wL
	qvEH2iWgrKxc/7KlqX3Z0dQ4djC19xcSDdOhWftP+3xA6O+j2aOZcPx9qrADo71ZXNFNIc1lmrEI
	poCKd0nL8oXm9+1iSojxZ/alteT5yWULgRNM2WL+tM+HrP7OIhKbcWHD3vMkj1rmXqZ+EpQjtbTn
	iMOduWfewOJsQfd5Xct14eRKbZkHPzCxzDdM3PM1o9Z3FOpe+9OBCmJfPff6Cog85xdHcFyJqKEv
	W+Y6l7fLzL99+DJ2zXQ9awjs+Ns5aHe9cn5fGqNcTEQ8HyWDsCIjD6Ky16w49IXDKLn1bQWhLv70
	4y9EHHdmlfsuVjLlkhVNeWRE7vUXGAljEnkliKyJKs/Hm1xHSBwC5fd9OW2Z81fPdj9WN7k0F2jm
	LTXfthfDlhsR1/UCbFTvgFRcmx+DrAXsKGsuM/aiwxCN/nz8T0D+tLSUM658wxHIfMCEMu+0hMhE
	FssKgmCalso5/O9dso6QcdwIwZ2TF0rKQgKTJYx8/ykTIP+NhS4UY5jzhICIER7AhBB0fdAy+8CJ
	b6aXRZG5y4DA/GpOGLz/Q899JO7Y7jffvKKylf2Gt5A5oZZvB1i25wwzOgNJ1Q2QOjWt1qzGAoJe
	/tJaHFoE6Mr9C3Iwpxb3MXW/BVdDgmJ3z8eiZFP5ZdX8+1Z+la/h0xuzho4F6CxKqHZhX2A7Zau/
	fhWcnNqDQuXwS2rvFXA99WjJE8U9gtPBZEns52ODMIRwh6PZ54YTwzvQrrmjfR/h2pkhIsLRsUFI
	Ykwf9BQc0WexySuBuhZwwhNzyAUup34o5tGLo+TOrMkEaODHK35ftwhscFN0FT4aspd5DdoVStak
	Ka2LvX8QSu1e1V7t1azNrB0wAfJhNrFzS6gyhSZV/3z4r59YeCmxceEHrNzURSeOn0Y1U/puxxGP
	XtxP21XuIIDbVJOSrX/7NoWmPEHsKVLPEe3Wz1GQgkvcURg19LT9wErouqLrzGpCGJFjSFVeuLi2
	5uTUSMX+sGxuhwNrWHDYuncTN2PgmrpmeYsKEHJoqloKrNTzccJbiLQjqhSB1mvp6yCk7zJwUrWe
	eQev5H/6bpXUH6Tq9GgIl4FtIx9P2o1Xk2gSyJcAdLXVOXeelhe8Jpw6TTCiXOrOy0uU0gMW19CG
	ILUDgHZATcyhELmlOfFbxWAUteUPGGj+Z/IEoeyUNDkjMMXy58OuQoA8KDwcr2GEnDOK0rapSgvV
	2RMJvuHkNJ85qbs+c3pRylBc82jsrF79UDcr3eiNFfjCnjmpLi3PhzhY7NtVEaRcjvBT/D7qD4bX
	AylJQz0kxTUjI7CcGLpI5IjsY9wkH25f8FJ0xLyqndfqVNJTYDDvVvN8HHZ02p86lQBj8X7TgnyP
	SIKc7/qJ8sXdvtCPKKNYbtzZD7e1jT0r2DYPHiFzLO+278YohswH6Bs21T4fBTbDQXsavtQA2kDb
	C2u1vzCIY6HAW/Cy8mQgOk5K747wxrf1EDWll8gPYpTQTAbvprmusyxhXgMR4PnACh5WX/f2fPF5
	9Zl/VfYbrP33jeDYcD5typ5tjgYTjnJKX7IN2UBKhPUau8Zab+cAXsrE26zX64zE5yMO5MHJ5w5z
	m/UlWsGe4ouEIX4F6pVZF6iLuO92riu+J6A3ttqObbmdvhLljxYXsz+816/nP2/VSJhbI7299uTe
	GgeTPmy53PnmXsio5zAcK8H3OELcGCTXNmBF/KmohyfSFgsJGbmB6uj8dYJfGjpJsmff27DeWa/X
	/je4Jlanfm3TYMV0iUbUMjCXT+MwDerySl9nWLvAueoH0q0aRGjpsM8hX386dGDpu/C88DIPkM/z
	8VLAMlOZ3fX1d6cvOuV23cjXXTnXv6Yp7/ox7Azss2GHmRyamO/mGhQA8uC+phoCD8bZ8ad6+FTN
	ct9G8OOBk9qgLfMCBa9tcM94iny7DMw4BVh4THc/i/BOHG8OOZ6mf6qxxG/RBRTrSnkfGUU5yiQD
	ntSLm28rW9SgyH+U3T1exvxRad1FdFD3jbs3g3BfcS5NrJxeIImuuLgJqho7uOwyj0niANGuoQFt
	QO/5OG/FdVD+qbz5YlD4dliUalnsXVQ2aw/X0u8w5DVAcuM5/YxM/shNjV4tmYMJw/QychXT4CXj
	6RsAvsAK8u4L14LYyTsrO0aU8lYUv/krTbrlgwRSV3aV8FJP7Ei7Ph71BiAVBxztHzLBrzLrVHQN
	rdVvz60i5Xmvnw8pfsFRxH3fnVSm1jeyxlvxzBCAClvMiquvnnEDb3LsSvbtHJLrsGT3l+3C42Ij
	7rZOhZsA4Fqc9uvuCxjuXm84o29ZHLEjjNI08dPg7i5nW74R/MbjEGiEPkDDBkHsif+2yd9144hA
	ymDTgEVNuwrEXkUVEP58XNh8tBO2AG21Vv0XJp2zkrEQhgI4ktA23j6tac7AVBmb/5KnBdNZ1Ecw
	YSHhuQyyTn8PUtpc3Dhfd2aZHktFxutYhADQZ3Fyph0AGipK3qMI+6+NTidsckVwBj6kEfOZobLg
	yXxmw53BydXBho6OfiaNw/fUOxf4goh/2QDNKvl9z+oXlX4725xMd/FTxTlmdPWg+nuDjRF99yqn
	++UzagS8o1qfUkIBzsasWSW3RRP6fPDGbyMNrypXABXpjZ4/KJHQ26dYZACE7cjAAQVAT3kngfjm
	+WaBxAsJKwO8Zb0RuNiC0MSLpMYtI497+ijRyHj7J32//fUwO82E08sIzDsGfocZfT0AkDAOh6CR
	VfJJ6tcZxpZFZETgprPGlZYh2ZpmiXhU4PPh0Nu+JWDZFiAoGYTnZxNUAPB5UQackDMFZ3K3xj21
	QT6B/tCTIteeJ+taX86YdhBVtjcKFhs8ADP4Zi/h+2lMbTn8w3Kkz7a2uyoYucXOFR/viowQeTvQ
	EF3BsgvA2ljTOV0vgCQQGmmNq5pa+eY0lsn1vj0fCnDlhOvFIUutTnHF1nrQCUiUFCjDABhst+SJ
	0RFK7tH1n3+Af422fw25zDynbdSU6fw38N75A/zfs/S//guW2Dt7Wg8AAA==#>
	#endregion
	
	<#
	    .NOTES
	    --------------------------------------------------------------------------------
	     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2019 v5.6.165
	     Generated on:       7/30/2019 3:36 PM
	     Generated by:       Support.newingha
	    --------------------------------------------------------------------------------
	    .DESCRIPTION
	        GUI script generated by PowerShell Studio 2019
	#>
	
	
	#----------------------------------------------
	#region Application Functions
	#----------------------------------------------
	
	#endregion Application Functions
	
	#----------------------------------------------
	# Generated Form Function
	#----------------------------------------------
	function Show-AboutForm_psf
	{
		
		#----------------------------------------------
		#region Import the Assemblies
		#----------------------------------------------
		[void][reflection.assembly]::Load('System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
		[void][reflection.assembly]::Load('System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
		#endregion Import Assemblies
		
		#----------------------------------------------
		#region Generated Form Objects
		#----------------------------------------------
		[System.Windows.Forms.Application]::EnableVisualStyles()
		$formAboutTheAuthor = New-Object 'System.Windows.Forms.Form'
		$picturebox1 = New-Object 'System.Windows.Forms.PictureBox'
		$labelWrittenInPowerShellS = New-Object 'System.Windows.Forms.Label'
		$labelAlannewinghamgmailco = New-Object 'System.Windows.Forms.Label'
		$labelEmail = New-Object 'System.Windows.Forms.Label'
		$labelAlanNewingham = New-Object 'System.Windows.Forms.Label'
		$labelAuthor = New-Object 'System.Windows.Forms.Label'
		$buttonOK = New-Object 'System.Windows.Forms.Button'
		$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
		#endregion Generated Form Objects
		
		#----------------------------------------------
		# User Generated Script
		#----------------------------------------------
		
		$formAboutTheAuthor_Load = {
			#TODO: Initialize Form Controls here
			
		}
		
		# --End User Generated Script--
		#----------------------------------------------
		#region Generated Events
		#----------------------------------------------
		
		$Form_StateCorrection_Load =
		{
			#Correct the initial state of the form to prevent the .Net maximized form issue
			$formAboutTheAuthor.WindowState = $InitialFormWindowState
		}
		
		$Form_Cleanup_FormClosed =
		{
			#Remove all event handlers from the controls
			try
			{
				$formAboutTheAuthor.remove_Load($formAboutTheAuthor_Load)
				$formAboutTheAuthor.remove_Load($Form_StateCorrection_Load)
				$formAboutTheAuthor.remove_FormClosed($Form_Cleanup_FormClosed)
			}
			catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
		}
		#endregion Generated Events
		
		#----------------------------------------------
		#region Generated Form Code
		#----------------------------------------------
		$formAboutTheAuthor.SuspendLayout()
		$picturebox1.BeginInit()
		#
		# formAboutTheAuthor
		#
		$formAboutTheAuthor.Controls.Add($picturebox1)
		$formAboutTheAuthor.Controls.Add($labelWrittenInPowerShellS)
		$formAboutTheAuthor.Controls.Add($labelAlannewinghamgmailco)
		$formAboutTheAuthor.Controls.Add($labelEmail)
		$formAboutTheAuthor.Controls.Add($labelAlanNewingham)
		$formAboutTheAuthor.Controls.Add($labelAuthor)
		$formAboutTheAuthor.Controls.Add($buttonOK)
		$formAboutTheAuthor.AcceptButton = $buttonOK
		$formAboutTheAuthor.AutoScaleDimensions = '6, 13'
		$formAboutTheAuthor.AutoScaleMode = 'Font'
		$formAboutTheAuthor.ClientSize = '284, 262'
		$formAboutTheAuthor.FormBorderStyle = 'FixedDialog'
		$formAboutTheAuthor.MaximizeBox = $False
		$formAboutTheAuthor.MinimizeBox = $False
		$formAboutTheAuthor.Name = 'formAboutTheAuthor'
		$formAboutTheAuthor.StartPosition = 'CenterScreen'
		$formAboutTheAuthor.Text = 'About the Author'
		$formAboutTheAuthor.add_Load($formAboutTheAuthor_Load)
		#
		# picturebox1
		#
		#region Binary Data
		$picturebox1.Image = [System.Convert]::FromBase64String('
R0lGODlhdAB0AIcAAAAAAAAAMwAAZgAAmQAAzAAA/wArAAArMwArZgArmQArzAAr/wBVAABVMwBV
ZgBVmQBVzABV/wCAAACAMwCAZgCAmQCAzACA/wCqAACqMwCqZgCqmQCqzACq/wDVAADVMwDVZgDV
mQDVzADV/wD/AAD/MwD/ZgD/mQD/zAD//zMAADMAMzMAZjMAmTMAzDMA/zMrADMrMzMrZjMrmTMr
zDMr/zNVADNVMzNVZjNVmTNVzDNV/zOAADOAMzOAZjOAmTOAzDOA/zOqADOqMzOqZjOqmTOqzDOq
/zPVADPVMzPVZjPVmTPVzDPV/zP/ADP/MzP/ZjP/mTP/zDP//2YAAGYAM2YAZmYAmWYAzGYA/2Yr
AGYrM2YrZmYrmWYrzGYr/2ZVAGZVM2ZVZmZVmWZVzGZV/2aAAGaAM2aAZmaAmWaAzGaA/2aqAGaq
M2aqZmaqmWaqzGaq/2bVAGbVM2bVZmbVmWbVzGbV/2b/AGb/M2b/Zmb/mWb/zGb//5kAAJkAM5kA
ZpkAmZkAzJkA/5krAJkrM5krZpkrmZkrzJkr/5lVAJlVM5lVZplVmZlVzJlV/5mAAJmAM5mAZpmA
mZmAzJmA/5mqAJmqM5mqZpmqmZmqzJmq/5nVAJnVM5nVZpnVmZnVzJnV/5n/AJn/M5n/Zpn/mZn/
zJn//8wAAMwAM8wAZswAmcwAzMwA/8wrAMwrM8wrZswrmcwrzMwr/8xVAMxVM8xVZsxVmcxVzMxV
/8yAAMyAM8yAZsyAmcyAzMyA/8yqAMyqM8yqZsyqmcyqzMyq/8zVAMzVM8zVZszVmczVzMzV/8z/
AMz/M8z/Zsz/mcz/zMz///8AAP8AM/8AZv8Amf8AzP8A//8rAP8rM/8rZv8rmf8rzP8r//9VAP9V
M/9VZv9Vmf9VzP9V//+AAP+AM/+AZv+Amf+AzP+A//+qAP+qM/+qZv+qmf+qzP+q///VAP/VM//V
Zv/Vmf/VzP/V////AP//M///Zv//mf//zP///wAAAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEB
AAAh+QQBAAD8ACwAAAAAdAB0AAAI/wABCBxIsKDBg/sS7jvIsKDChxAjJiT4kKLChhgzatwIoCJH
hxJDehQ4suPFjyhTIjypUqTLhQNLllRJ8+NMmy9DWpwYk2XNhjl19oy4EybJoDyPJjXpsijSpU6f
Rl0qU+pQo0xFTg3K8CnErUW3ClWKNafYl129+hyb9SzRq27LqoUKN2PVt2TD1sXI9i7WtHTz2l0r
Ua/gw0AL7207ODBjvoTxPp5802DfyH9XOq4MkqpixH41Xvbs2HDnzJYxA5YrWbRVxKtjN2aNmvLn
jV5Ny05dejFnv5xXm128+7Rr0rWB+zzOlbjm5Muf6/4JOjpv2syLFw9OM/Ts6de1S/93Tt07ZOTZ
x5/HTt04efew1Z/O/d584tZXlSMV/nqyae5k/XbbXJsRCJ5tvQVoXVb6NXcdffFVlyCDC46mVnv3
sSehhghyiOGHvqkWInoj1gZieSJu+F+K/p2IoX0wsmjfiwQOp+B++bEYV408opUjjjd6+GOPRNpI
IZBHChlkkUwOaOCQBzYpmZEAughfiy3dFteBVspXJXMCNvVel+GNiRN+S+pI5nYLomSheBuGyeOa
6ZVpZ5L8zUXnd/KtiGaSEO7ZZ32YyVmjoLhpWSKYbS46aJp/suWniVDyGSGWgCoaJJsTSuplhaAi
CdannWp6pZx5ajVbg55eWiWqZ1L/+mChPt7JJaET3jorckZG2airv17JKK+1CmsmsLkem+iUtEba
36SBfllpnKYGCm1/0m5aYquZOkssktniuW21z44LbrMcGhrspKmu+SauX8Xq6580MkvirrKeGmq8
Xb6LLL/LKikuiIeS2etzr+67o6n1qrpewgV+66CVB+Nbp756Glxsu5Yaa/GQEKdLrr0XxspqsDF6
C3DBHFnILbvTzoduxRmeXOq9A8ssMc1FLpzsneruPPOTkALsppraFu3zxNbKC6/NtPUMMsMdBx21
kzhfzDPRHR59c77Xqhwt0hlerPXGU4upotPreX212NiSDWe3DusMdnsuxy202nYj9pr3uXvXPeqe
fzM9NN+D01k4lejOO7HZHTtuteRot822xzknbvXLj5bdObf+2s25rZE/vS68MLeMtcBuh8wp6wjL
ePrDKCvsqOok6xqw66TC/vHaKJIsJXQ/d73q6osTOffrw65c7PCw4u473VumPWfnzB8vPNXB3610
7BFPH67brY9s9O2e9zs79eATL/765JtsfvSYUg6487n3nmqDYRu+fdboq17SOjS2/wlsRtbT3OHq
VjjH2Q9/ENQdAr9Hu+KVL3+W+9foMncixn3tgSEbn/wwmD5M0SxxLvJgvqA2uZglj28TxNjjXIi8
BYaOd0Vr4QBfyHFAuZlLcDQ04NJStsLGme6D2juf9M5GQhRiL4HdqZ3EHgg5fInwUv2jYumsCD/r
8RCHopOi+5qnwhMeUYmYC6HeZkg6CpZQglxrWhvZl0HMpdCIOTRfw3QXvx1yjY9V62Idv6hHvPkw
S1P0YiG7V5SAAAA7')
		#endregion
		$picturebox1.Location = '84, 41'
		$picturebox1.Name = 'picturebox1'
		$picturebox1.Size = '116, 116'
		$picturebox1.TabIndex = 6
		$picturebox1.TabStop = $False
		#
		# labelWrittenInPowerShellS
		#
		$labelWrittenInPowerShellS.AutoSize = $True
		$labelWrittenInPowerShellS.Location = '15, 232'
		$labelWrittenInPowerShellS.Name = 'labelWrittenInPowerShellS'
		$labelWrittenInPowerShellS.Size = '176, 17'
		$labelWrittenInPowerShellS.TabIndex = 5
		$labelWrittenInPowerShellS.Text = 'Written in PowerShell Studio 2019'
		$labelWrittenInPowerShellS.UseCompatibleTextRendering = $True
		#
		# labelAlannewinghamgmailco
		#
		$labelAlannewinghamgmailco.AutoSize = $True
		$labelAlannewinghamgmailco.Location = '89, 207'
		$labelAlannewinghamgmailco.Name = 'labelAlannewinghamgmailco'
		$labelAlannewinghamgmailco.Size = '150, 17'
		$labelAlannewinghamgmailco.TabIndex = 4
		$labelAlannewinghamgmailco.Text = 'alan.newingham@gmail.com'
		$labelAlannewinghamgmailco.UseCompatibleTextRendering = $True
		#
		# labelEmail
		#
		$labelEmail.AutoSize = $True
		$labelEmail.Location = '46, 207'
		$labelEmail.Name = 'labelEmail'
		$labelEmail.Size = '36, 17'
		$labelEmail.TabIndex = 3
		$labelEmail.Text = 'Email:'
		$labelEmail.UseCompatibleTextRendering = $True
		#
		# labelAlanNewingham
		#
		$labelAlanNewingham.AutoSize = $True
		$labelAlanNewingham.Location = '121, 190'
		$labelAlanNewingham.Name = 'labelAlanNewingham'
		$labelAlanNewingham.Size = '90, 17'
		$labelAlanNewingham.TabIndex = 2
		$labelAlanNewingham.Text = 'Alan Newingham'
		$labelAlanNewingham.UseCompatibleTextRendering = $True
		#
		# labelAuthor
		#
		$labelAuthor.AutoSize = $True
		$labelAuthor.Location = '73, 190'
		$labelAuthor.Name = 'labelAuthor'
		$labelAuthor.Size = '41, 17'
		$labelAuthor.TabIndex = 1
		$labelAuthor.Text = 'Author:'
		$labelAuthor.UseCompatibleTextRendering = $True
		#
		# buttonOK
		#
		$buttonOK.Anchor = 'Bottom, Right'
		$buttonOK.DialogResult = 'OK'
		$buttonOK.Location = '197, 227'
		$buttonOK.Name = 'buttonOK'
		$buttonOK.Size = '75, 23'
		$buttonOK.TabIndex = 0
		$buttonOK.Text = '&OK'
		$buttonOK.UseCompatibleTextRendering = $True
		$buttonOK.UseVisualStyleBackColor = $True
		$picturebox1.EndInit()
		$formAboutTheAuthor.ResumeLayout()
		#endregion Generated Form Code
		
		#----------------------------------------------
		
		#Save the initial state of the form
		$InitialFormWindowState = $formAboutTheAuthor.WindowState
		#Init the OnLoad event to correct the initial state of the form
		$formAboutTheAuthor.add_Load($Form_StateCorrection_Load)
		#Clean up the control events
		$formAboutTheAuthor.add_FormClosed($Form_Cleanup_FormClosed)
		#Show the Form
		return $formAboutTheAuthor.ShowDialog()
		
	} #End Function
	
	
	if ($RichTextBox1.text.Trim() -ne "")
	{
		$buttonCopyToClipboard.Enabled = $true
	}
	
	#----------------------------------------------
	# Generated Form Function
	#----------------------------------------------
	
	
	function encryptAll
	{
		$Text = $RichTextBox1.text
		$Bytes = [System.Text.Encoding]::Unicode.GetBytes($Text)
		$EncodedText = [Convert]::ToBase64String($Bytes)
		$RichTextBox1.text = $EncodedText
	}
	
	function decryptAll
	{
		$EncodedText = $RichTextBox1.text
		$DecodedText = [System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($EncodedText))
		$RichTextBox1.text = $DecodedText
	}
	
	function ConvertImage
	{
		$Texta = $TextBox1.text
		$EncodedText = [convert]::ToBase64String((Get-Content $texta -Encoding byte))
		$RichTextBox1.text = $EncodedText
	}
	
	function decodeImage
	{
		$b64 = $RichTextBox1.text
		$filename = $TextBox1.text
		$bytes = [Convert]::FromBase64String($b64)
		$DecodedText = [IO.File]::WriteAllBytes($filename, $bytes)
		$RichTextBox1.text = $DecodedText
	}
	
	$labelPasteTextBelow_Click={
		#TODO: Place custom script here
		
	}
	
	$linklabelCreatedByAlanNewingh_LinkClicked=[System.Windows.Forms.LinkLabelLinkClickedEventHandler]{
	#Event Argument: $_ = [System.Windows.Forms.LinkLabelLinkClickedEventArgs]
		#TODO: Place custom script here
		Show-AboutForm_psf | Out-Null
	}
	
	$buttonEncode64_Click={
		encryptAll
	}
	
	$buttonDecode64_Click={
		decryptAll
	}
	
	$buttonCopyToClipboard_Click={
		#TODO: Place custom script here
		#[System.Windows.Forms.Clipboard]::SetText($RichTextBox1.text.Trim())
		$copyText = $RichTextBox1.Text.Trim()
		[System.Windows.Forms.Clipboard]::SetText($copyText)
		
		if ([System.Windows.Forms.Clipboard]::ContainsText() -AND
			[System.Windows.Forms.Clipboard]::GetText() -eq $copyText)
		{
			$statusbar1.Text = "Copied to clipboard."
			$statusbar1.Visible = $true
			Start-Sleep -Seconds 2
			$statusbar1.Visible = $false
		}
	}
	
	$buttonEncodeImage_Click={
		ConvertImage
	}
	
	$textbox1_TextChanged={
		
	}
	
	$buttonDecodeImage_Click={
		DecodeImage
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formFr33Bas3V001.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonEncodeImage.remove_Click($buttonEncodeImage_Click)
			$textbox1.remove_TextChanged($textbox1_TextChanged)
			$buttonDecodeImage.remove_Click($buttonDecodeImage_Click)
			$buttonEncode64.remove_Click($buttonEncode64_Click)
			$buttonDecode64.remove_Click($buttonDecode64_Click)
			$buttonCopyToClipboard.remove_Click($buttonCopyToClipboard_Click)
			$linklabelCreatedByAlanNewingh.remove_LinkClicked($linklabelCreatedByAlanNewingh_LinkClicked)
			$formFr33Bas3V001.remove_Load($formFr33Bas3V001_Load)
			$formFr33Bas3V001.remove_Load($Form_StateCorrection_Load)
			$formFr33Bas3V001.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formFr33Bas3V001.SuspendLayout()
	$groupbox1.SuspendLayout()
	$groupbox2.SuspendLayout()
	#
	# formFr33Bas3V001
	#
	$formFr33Bas3V001.Controls.Add($groupbox2)
	$formFr33Bas3V001.Controls.Add($groupbox1)
	$formFr33Bas3V001.Controls.Add($statusbar1)
	$formFr33Bas3V001.Controls.Add($buttonCopyToClipboard)
	$formFr33Bas3V001.Controls.Add($linklabelCreatedByAlanNewingh)
	$formFr33Bas3V001.Controls.Add($labelAltF4ForDirections)
	$formFr33Bas3V001.Controls.Add($labelWelcomeToFr33Bas3The)
	$formFr33Bas3V001.AutoScaleDimensions = '6, 13'
	$formFr33Bas3V001.AutoScaleMode = 'Font'
	$formFr33Bas3V001.ClientSize = '404, 461'
	$formFr33Bas3V001.Name = 'formFr33Bas3V001'
	$formFr33Bas3V001.Text = 'Fr33Bas3 v. 0.0.3'
	$formFr33Bas3V001.add_Load($formFr33Bas3V001_Load)
	#
	# groupbox2
	#
	$groupbox2.Controls.Add($buttonEncodeImage)
	$groupbox2.Controls.Add($textbox1)
	$groupbox2.Controls.Add($buttonDecodeImage)
	$groupbox2.Controls.Add($labelImageLocation)
	$groupbox2.Location = '12, 29'
	$groupbox2.Name = 'groupbox2'
	$groupbox2.Size = '378, 100'
	$groupbox2.TabIndex = 15
	$groupbox2.TabStop = $False
	$groupbox2.Text = 'Image'
	$groupbox2.UseCompatibleTextRendering = $True
	#
	# buttonEncodeImage
	#
	$buttonEncodeImage.Location = '191, 65'
	$buttonEncodeImage.Name = 'buttonEncodeImage'
	$buttonEncodeImage.Size = '89, 23'
	$buttonEncodeImage.TabIndex = 9
	$buttonEncodeImage.Text = 'Encode Image'
	$buttonEncodeImage.UseCompatibleTextRendering = $True
	$buttonEncodeImage.UseVisualStyleBackColor = $True
	$buttonEncodeImage.add_Click($buttonEncodeImage_Click)
	#
	# textbox1
	#
	$textbox1.Location = '100, 18'
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '180, 20'
	$textbox1.TabIndex = 11
	$textbox1.add_TextChanged($textbox1_TextChanged)
	#
	# buttonDecodeImage
	#
	$buttonDecodeImage.Location = '283, 65'
	$buttonDecodeImage.Name = 'buttonDecodeImage'
	$buttonDecodeImage.Size = '89, 23'
	$buttonDecodeImage.TabIndex = 13
	$buttonDecodeImage.Text = 'Decode Image'
	$buttonDecodeImage.UseCompatibleTextRendering = $True
	$buttonDecodeImage.UseVisualStyleBackColor = $True
	$buttonDecodeImage.add_Click($buttonDecodeImage_Click)
	#
	# labelImageLocation
	#
	$labelImageLocation.AutoSize = $True
	$labelImageLocation.Location = '6, 21'
	$labelImageLocation.Name = 'labelImageLocation'
	$labelImageLocation.Size = '88, 17'
	$labelImageLocation.TabIndex = 12
	$labelImageLocation.Text = 'Image Location: '
	$labelImageLocation.UseCompatibleTextRendering = $True
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($richtextbox1)
	$groupbox1.Controls.Add($buttonEncode64)
	$groupbox1.Controls.Add($buttonDecode64)
	$groupbox1.Location = '4, 162'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Size = '392, 245'
	$groupbox1.TabIndex = 14
	$groupbox1.TabStop = $False
	$groupbox1.Text = 'Text'
	$groupbox1.UseCompatibleTextRendering = $True
	#
	# richtextbox1
	#
	$richtextbox1.Location = '6, 48'
	$richtextbox1.Name = 'richtextbox1'
	$richtextbox1.Size = '380, 187'
	$richtextbox1.TabIndex = 0
	$richtextbox1.Text = ''
	#
	# buttonEncode64
	#
	$buttonEncode64.Location = '230, 19'
	$buttonEncode64.Name = 'buttonEncode64'
	$buttonEncode64.Size = '75, 23'
	$buttonEncode64.TabIndex = 2
	$buttonEncode64.Text = 'Encode64'
	$buttonEncode64.UseCompatibleTextRendering = $True
	$buttonEncode64.UseVisualStyleBackColor = $True
	$buttonEncode64.add_Click($buttonEncode64_Click)
	#
	# buttonDecode64
	#
	$buttonDecode64.Location = '311, 19'
	$buttonDecode64.Name = 'buttonDecode64'
	$buttonDecode64.Size = '75, 23'
	$buttonDecode64.TabIndex = 3
	$buttonDecode64.Text = 'Decode64'
	$buttonDecode64.UseCompatibleTextRendering = $True
	$buttonDecode64.UseVisualStyleBackColor = $True
	$buttonDecode64.add_Click($buttonDecode64_Click)
	#
	# statusbar1
	#
	$statusbar1.Location = '0, 439'
	$statusbar1.Name = 'statusbar1'
	$statusbar1.Size = '404, 22'
	$statusbar1.TabIndex = 8
	#
	# buttonCopyToClipboard
	#
	$buttonCopyToClipboard.Location = '287, 413'
	$buttonCopyToClipboard.Name = 'buttonCopyToClipboard'
	$buttonCopyToClipboard.Size = '109, 23'
	$buttonCopyToClipboard.TabIndex = 7
	$buttonCopyToClipboard.Text = 'Copy to Clipboard'
	$buttonCopyToClipboard.UseCompatibleTextRendering = $True
	$buttonCopyToClipboard.UseVisualStyleBackColor = $True
	$buttonCopyToClipboard.add_Click($buttonCopyToClipboard_Click)
	#
	# linklabelCreatedByAlanNewingh
	#
	$linklabelCreatedByAlanNewingh.Location = '63, 552'
	$linklabelCreatedByAlanNewingh.Name = 'linklabelCreatedByAlanNewingh'
	$linklabelCreatedByAlanNewingh.Size = '100, 23'
	$linklabelCreatedByAlanNewingh.TabIndex = 6
	$linklabelCreatedByAlanNewingh.TabStop = $True
	$linklabelCreatedByAlanNewingh.Text = 'Created by: Alan Newingham'
	$linklabelCreatedByAlanNewingh.TextAlign = 'MiddleCenter'
	$linklabelCreatedByAlanNewingh.UseCompatibleTextRendering = $True
	$linklabelCreatedByAlanNewingh.add_LinkClicked($linklabelCreatedByAlanNewingh_LinkClicked)
	#
	# labelAltF4ForDirections
	#
	$labelAltF4ForDirections.AutoSize = $True
	$labelAltF4ForDirections.Location = '90, 100'
	$labelAltF4ForDirections.Name = 'labelAltF4ForDirections'
	$labelAltF4ForDirections.Size = '105, 17'
	$labelAltF4ForDirections.TabIndex = 5
	$labelAltF4ForDirections.Text = 'Alt+F4 for directions'
	$labelAltF4ForDirections.UseCompatibleTextRendering = $True
	#
	# labelWelcomeToFr33Bas3The
	#
	$labelWelcomeToFr33Bas3The.AutoSize = $True
	$labelWelcomeToFr33Bas3The.Location = '77, 9'
	$labelWelcomeToFr33Bas3The.Name = 'labelWelcomeToFr33Bas3The'
	$labelWelcomeToFr33Bas3The.Size = '252, 17'
	$labelWelcomeToFr33Bas3The.TabIndex = 4
	$labelWelcomeToFr33Bas3The.Text = 'Welcome to Fr33Bas3 the Base64 Encoding Tool'
	$labelWelcomeToFr33Bas3The.UseCompatibleTextRendering = $True
	$groupbox2.ResumeLayout()
	$groupbox1.ResumeLayout()
	$formFr33Bas3V001.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formFr33Bas3V001.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formFr33Bas3V001.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formFr33Bas3V001.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formFr33Bas3V001.ShowDialog()

} #End Function

#Call the form
Show-Fr33Bas3_psf | Out-Null